import React from 'react';
import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head';
import PropTypes from 'prop-types';

import Navbar from '../../components/Navbar';
import Container from '../../components/Container';

import styles from '../../styles/Pokemon.module.scss'


export default function Pokemon({ pokemon }) {
    return (
        <Container>
            <div className={styles.container}>
                <Head>
                    <title>Pokemon | {pokemon.name}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/logo-pokemon.svg" />
                </Head>

                <Navbar></Navbar>


                <main>
                    <img src={pokemon.sprites.front_default} alt="Imagem do Pokemon" />

                    <h2>{pokemon.name}</h2>

                    <Link href="/">
                        <a>Voltar a pagina anterior</a>
                    </Link>
                </main>

                <footer>
                    <a
                        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        Powered by{' Thiago Henrique Fragata '}
                        <span className={styles.logo}>
                            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                        </span>
                    </a>
                </footer>
            </div>
        </Container>
    );
}

Pokemon.propTypes = {
    pokemon: PropTypes.shape({
        name: PropTypes.string,
        sprites: PropTypes.shape({
            front_default: PropTypes.string,
        }),
    }).isRequired,
};

export async function getStaticPaths() {
    return {
        paths: new Array(151).fill(null).map((_, index) => (
            { params: { id: `${index + 1}` } }
        )),
        fallback: false
    };
}

export async function getStaticProps({ params }) {
    // connecting pokeAPI
    const pokemon = await fetch(`https://pokeapi.co/api/v2/pokemon/${params.id}`)
        .then((respostaDoServer) => {
            if (respostaDoServer.ok) {
                return respostaDoServer.json();
            }

            throw new Error("Deu problema!")
        })
        // get response in object JSON
        .then((RespostaEmObjeto) => {
            return RespostaEmObjeto;
        });

    return {
        props: {
            pokemon,
        },
        // will be passed to the page component as props
    };
}