import Head from 'next/head'

import Navbar from '../components/Navbar';
import Container from '../components/Container';

import styles from '../styles/About.module.scss'


export default function Sobre() {
    return (
        <Container>
            <div className={styles.container}>
                <Head>
                    <title>Pokemon | About</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/logo-pokemon.svg" />
                </Head>

                <Navbar></Navbar>

                <main>
                    <h1>About me</h1>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at finibus nulla, a viverra turpis. In aliquam justo vitae tincidunt maximus. In hac habitasse platea dictumst. Cras ornare ornare diam, et pellentesque mi eleifend et. Mauris aliquet auctor scelerisque. Maecenas commodo magna at turpis pulvinar, id vehicula tellus maximus. Praesent ex ipsum, egestas vitae hendrerit eget, iaculis non quam. Integer at sollicitudin nulla. Proin egestas lectus et velit iaculis, ac laoreet nisi posuere.
                </p>
                    <p>Pellentesque mollis et nibh in rutrum. Duis sit amet eleifend enim, in imperdiet velit. Pellentesque a magna eget nunc rutrum tincidunt. Fusce nisl risus, consectetur nec sem eu, consectetur gravida nunc. Maecenas vel ultrices odio. Aenean tempor blandit felis, sit amet interdum massa vulputate at. Sed dictum non ante in dignissim. In pharetra aliquam metus, feugiat scelerisque ipsum ultricies non. Nam sagittis mauris eu erat dapibus condimentum. In ultricies, massa nec eleifend malesuada, diam purus commodo lectus, sed lacinia nulla risus id erat. Nunc placerat ligula non libero fringilla, non varius mi convallis. Integer at aliquet enim. Suspendisse potenti.</p>
                    <p>Aliquam id tristique est, blandit cursus enim. Vivamus quis nisi est. Cras feugiat mollis quam in eleifend. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec maximus enim vel metus sagittis, venenatis faucibus sem iaculis. Nunc eu augue non risus blandit fringilla ac nec risus. Integer et mauris at nisl consectetur ultricies. Sed lacinia purus nulla, vel semper odio iaculis ac. Sed condimentum lobortis sem ut pharetra. Pellentesque dignissim quam non pulvinar vestibulum. Vestibulum ut volutpat dui. Aliquam nec velit consequat nisl aliquet interdum ac id orci. Nam erat tortor, faucibus vel lacus ac, maximus pretium purus. Suspendisse potenti. Aliquam in mattis ex, at tincidunt mi.</p>
                </main>
            </div>
        </Container>
    );
}