import Head from 'next/head'
import Image from 'next/image'

import Link from '../components/Link';
import Navbar from '../components/Navbar';
import Container from '../components/Container';

import styles from '../styles/Home.module.scss'

export default function Home(props) {
  const { pokemons } = props;


  return (
    <Container>
      <div className={styles.container}>
        <Head>
          <title>Pokemon</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo-pokemon.svg" />
        </Head>

        <Navbar></Navbar>

        <main>

          <h1>Lista de pokemons</h1>

          <div className={styles.pokemons}>

            {pokemons.map((pokemon) => (
              <div key={pokemon.entry_number}>
                <Link href={`/pokemon/${pokemon.entry_number}`}>
                  {pokemon.pokemon_species.name}
                </Link>
              </div>
            ))}

          </div>
        </main>

        <footer>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' Thiago Henrique Fragata '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </Container>
  )
}

export async function getStaticProps() {
  // connecting pokeAPI
  const pokemons = await fetch("https://pokeapi.co/api/v2/pokedex/2/")
    .then((respostaDoServer) => {
      if (respostaDoServer.ok) {
        return respostaDoServer.json();
      }
    })
    // get response in object JSON
    .then((RespostaEmObjeto) => {
      return RespostaEmObjeto.pokemon_entries;
    });

  return {
    props: {
      pokemons,
    },
    revalidate: 60 * 60 * 24,
  };
}
